# Generated by Django 2.1.5 on 2020-10-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket_add',
        ),
        migrations.DeleteModel(
            name='Basket_remove',
        ),
    ]
