# Generated by Django 2.1.5 on 2020-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
            ],
        ),
    ]
